### ISSUE TITLE
Create Book

### ISSUE THREAD

**Issue by rmzzz** [AAU-ASE24W-group-E/crowd-library#1]
**As a Book Owner,**
**I want create a book if it is not yet in the crowd library**
**So that I can _later_ add it to my personal library.**

**Acceptance Criteria:**
- [ ] If I notice I cannot find the book in the crowd library I want to have the option to create it
- [ ] The creation should be able to happen by ISBN (API)
- [ ] The creation should be able to happen by form (manually)
- [ ] I want to submit my created book
- [ ] After submitting the created book I should be able to add it to my personal library (#2 )

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Necessary tests are written and pass.
- [ ] Documentation is updated, if applicable.
- [ ] Feature is deployed to the [environment name].

**Affected - check if implemented:**
- [x] FE
- [x] BE - cl-book-service

**Comment by elikonrad-aau** [comment]
Book creation by form -> Should be allow it in frontend for users to add books manually?
