### ISSUE TITLE
Log in User (backend)

### ISSUE THREAD

**Issue by djamn** [AAU-ASE24W-group-E/crowd-library#7]
**As a user**
**I want to be able to log in**
**So that I can manage my rented books and so on.**

**Acceptance Criteria:**
- [ ] User is logged in with email or username (default)
- [ ] (Opt.) user can also log in with GitHub and Google (ThirdParty)
- [ ] Session is saved
- [ ] All data of the specific user will be inserted into the webpage
- [ ] Backend-Frontend connection

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Necessary tests are written and pass.
- [ ] Documentation is updated, if applicable.
- [ ] Feature is deployed to the [environment name].

**Affected - check if implemented:**
- [ ] FE
- [ ] BE - cl-user-service

**Comment by jublebi** [comment]
Actually already done in the user service in the register user service issue
